### ISSUE TITLE
Portable version 1.5.11-4 does not read settings from portable path

### ISSUE THREAD

**Issue by cjom** [portapps/cryptomator-portable#10]
### Behaviour
Portable version looks for settings in ~/AppData/Roaming/Cryptomator/settings.json and because there is none it loads blank configuration.
#### Steps to reproduce this issue

1. Install v1.5.11-4 over previous version 1.5.8-3
2. Execute portable Cryptomator.

#### Expected behaviour

It should loads previously configured vaults.

#### Actual behaviour

The list of vaults is empty.

### Configuration

Portable version 1.5.11-4 64 bits
Windows 10 Pro 64 bits

### Logs

[cryptomator-portable.log](https://github.com/portapps/cryptomator-portable/files/5719322/cryptomator-portable.log)

**Comment by cjom** [comment]
I also found where the problem is and fixed it (at least it's working again as expected).

in the file app/app/Cryptomator.cfg just changed
```
java-options=-Dcryptomator.logDir=~/AppData/Roaming/Cryptomator
java-options=-Dcryptomator.settingsPath=~/AppData/Roaming/Cryptomator/settings.json
java-options=-Dcryptomator.ipcPortPath=~/AppData/Roaming/Cryptomator/ipcPort.bin
java-options=-Dcryptomator.keychainPath=~/AppData/Roaming/Cryptomator/keychain.json
```

to:
```
java-options=-Dcryptomator.logDir==../data/log
java-options=-Dcryptomator.settingsPath=../data/settings.json
java-options=-Dcryptomator.ipcPortPath=../data/ipcPort.bin
java-options=-Dcryptomator.keychainPath=../data/keychain.json
```

as it was in older version

**Comment by crazy-max** [comment]
@cjom Thanks for your report, this should be fixed in latest release: https://portapps.io/app/cryptomator-portable/#download
