### ISSUE TITLE
webdav file size limit?

### ISSUE THREAD

**Issue by Wanting-Ranked-Lavender** [portapps/cryptomator-portable#13]
### Behaviour
Files more than a certain size (suspected to be 50MB) cannot be read.

#### Steps to reproduce this issue

1. Save a file more than, say, 50MB to a vault.
2. Cannot open it thereafter.

#### Expected behaviour

> Tell me what should happen

It should be able to be opened just like in the installed version.

#### Actual behaviour

> Tell me what happens instead

Cannot open.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
1.5.11-5

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 Home 64 bits

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
@Wanting-Ranked-Lavender Don't think that's related to the portability but the app itself. Please open an issue about this on the main repo: https://github.com/cryptomator/cryptomator
