### ISSUE TITLE
cryptomator portable app doesn't start in Windows 8.1 Pro

### ISSUE THREAD

**Issue by heiner10** [portapps/cryptomator-portable#15]
Hello,

I face the issue that cryptomator portable app doesn't start in Windows 8.1 Pro Version 6.3 (build 9600).
Error message: "Command failed"

According to the log it seems there is a problem with java.

[cryptomator-portable.log](https://github.com/portapps/cryptomator-portable/files/7604027/cryptomator-portable.log)

**Comment by ntr4ef** [comment]
Hello,

I am experiencing the same issue on Win7 Pro Version 6.1 (Build 7601).

I have updated (and removed old) Java environments. I am able to run Cryptomator Portable 1.5.16-7 without any trouble, however.

[cryptomator-portable.txt](https://github.com/portapps/cryptomator-portable/files/7774803/cryptomator-portable.txt)

**Comment by crazy-max** [comment]
Minimum supported is Win10: https://portapps.io/app/cryptomator-portable/#infos
