### ISSUE TITLE
cryptomator portable 1.6.1-8 does not load settings on system start up

### ISSUE THREAD

**Issue by marcus3333** [portapps/cryptomator-portable#19]
Hi guys,

thanks for the amazing work.

I just faced an repeatable issue:
When Cryptomator starts on system start up on Windows 10 Enterprise, it does not load the settings.
After exiting Cryptomator and starting it once again, all setting were loaded.

Greetings

**Comment by crazy-max** [comment]
@marcus3333 If you have enabled "Start on startup" through the UI then yes it's normal that it doesn't work because it will not run the `cryptomator-portable.exe` wrapper. Check in the Windows Task Scheduler setting the path to the exe and set it to `cryptomator-portable.exe`.
