### ISSUE TITLE
Handle Parameter for Cryptomator

### ISSUE THREAD

**Issue by tarkett2018** [portapps/cryptomator-portable#2]
### Behaviour
I want to set/overwrite the following JavaOptions Parameter in Cryptomator.

[JavaOptions]
-Dcryptomator.logDir=%temp%/cryptomator
-Dcryptomator.settingsPath=../abc/settings.json
-Dcryptomator.ipcPortPath=../xsd/ipcPort.bin
-Dcryptomator.keychainPath=T:/keychain.json
-Dprism.order=sw

How it is to configure in cryptomator-portable that it will be set correct in the file Cryptomator.cfg?

#### Steps to reproduce this issue

1. I configure the file Cryptomator.cfg from Cryptomator as I want.
2. Start cryptomator-portable

#### Expected behaviour

My changes should be persist or must be configured on another side

#### Actual behaviour

My changes in the Cryptomator.cfg file are lost.

### Configuration

Version 1.5.6-1 win64

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro x64

**Winver screenshot** : Version 2004 (Build 19041.388)

**Comment by crazy-max** [comment]
@tarkett2018 These settings are already handled by Portapps and cannot be customized.
